import { Inter, Roboto } from 'next/font/google';
import './globals.css';
import Header from './../components/Header';
import Chatbot from '@/components/Chatbot';
import useServerDarkMode from '@/hooks/use-server-dark-mode';

const inter = Inter({ subsets: ['latin'] });
const roboto = Roboto({
  weight: ['400', '700'],
  subsets: ['latin'],
});

export const metadata = {
  title: {
    template: '%s | Lukas next app',
    default: 'Lukas Next App',
  },
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  const theme = useServerDarkMode();
  return (
    <html lang='en' className={theme}>
      <body className={roboto.className}>
        <Header />
        <main className='mt-12'>{children} </main>
        <Chatbot />
      </body>
    </html>
  );
}
